[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/en-US/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/en-GB/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/de-DE/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/es-ES/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/fr-FR/*"
  to = "/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
